home:
  hosts:
    127.0.0.1:
      ansible_connection: local
      ansible_user: charlesgoncalves
      ansible_become_pass: cfg@M4c


l1v4-18:
  hosts:
    10.3.1.219:
      ansible_user: xen
      ansible_become_pass: x3n123

xen3:
  hosts:
    cfgxen3.dei.uc.pt:
      ansible_user: charles  # Override the ansible_user for xen3 host
      ansible_python_interpreter: /usr/bin/python

xen4:
  hosts:
    cfgxen4.dei.uc.pt:
      ansible_user: xen
      ansible_become_pass: cfg@X3n

xen5:
  hosts:
    cfgxen5.dei.uc.pt:
      ansible_user: xen

xenservers:
  children:
    xen3:
    xen4:
    xen5:
